name: financeapp_mobile
description: FinanceApp mobile
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  intl: ^0.20.2
  fl_chart: ^0.69.0
  share_plus: ^11.1.0
  dio: ^5.9.0
  flutter_secure_storage: ^4.2.1
  jwt_decoder: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
